#!/usr/bin/env python3
"""Curate R6 training data targeting repetition reduction.

Three-layer strategy:
  Layer 1: Clean positive reasoning traces (Mixture-of-Thoughts + OpenThoughts)
           — teaches baseline non-repeating reasoning behavior
  Layer 2: R5 instruction/format data (carry forward what works)
           — preserves instruction following and format compliance
  Layer 3: Anti-loop negative examples from model's own failures
           — custom data targeting the specific repetition failure mode

Data sources:
  - open-r1/Mixture-of-Thoughts (350k verified reasoning traces)
  - open-thoughts/OpenThoughts-114k (DeepSeek-R1 traces, verified)
  - R5 format/instruction/conversational data (carry forward)
  - Anti-loop data generated by scripts/generate_antiloop.py

Usage:
  python scripts/curate_r6.py [--antiloop-file data/splits/antiloop_pairs.jsonl]
"""
from __future__ import annotations

import hashlib
import json
import random
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPLITS = ROOT / "data" / "splits"
SEED = 42


def _sha(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def sharegpt_to_messages(convs: list[dict]) -> list[dict]:
    role_map = {"human": "user", "gpt": "assistant", "system": "system",
                "user": "user", "assistant": "assistant"}
    return [{"role": role_map.get(c.get("from", ""), c.get("from", "")),
             "content": c.get("value", c.get("content", ""))}
            for c in convs]


# ---------------------------------------------------------------------------
# Repetition detection (for filtering)
# ---------------------------------------------------------------------------

def has_repetition(text: str, threshold: float = 0.08) -> bool:
    """Quick check if text has repetition loops."""
    if not text or len(text) < 100:
        return False
    sentences = re.split(r'[.!?\n]+', text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 20]
    if len(sentences) < 3:
        return False
    from collections import Counter
    counts = Counter(sentences)
    repeat_ratio = sum(c - 1 for c in counts.values() if c >= 2) / len(sentences)
    return repeat_ratio > threshold


# ---------------------------------------------------------------------------
# Layer 1: Clean reasoning traces
# ---------------------------------------------------------------------------

def load_mixture_of_thoughts(n: int) -> list[dict]:
    """Load from open-r1/Mixture-of-Thoughts — 350k verified traces."""
    from datasets import load_dataset

    print(f"[mot] Loading open-r1/Mixture-of-Thoughts...", flush=True)
    ds = load_dataset("open-r1/Mixture-of-Thoughts", "all", split="train",
                      streaming=True)

    rng = random.Random(SEED)
    results = []
    scanned = 0
    skipped_rep = 0
    skipped_long = 0

    for row in ds:
        scanned += 1
        if scanned > n * 10 and len(results) >= n:
            break
        if scanned > 200000:
            break

        # Random subsample
        if rng.random() > 0.1:
            continue

        msgs = row.get("messages", [])
        if not msgs:
            convs = row.get("conversations", [])
            if convs:
                msgs = sharegpt_to_messages(convs)
        if len(msgs) < 2:
            continue

        # Get assistant response
        asst = next((m for m in msgs if m.get("role") == "assistant"), None)
        if not asst:
            continue
        content = asst.get("content", "")

        # FILTER: Skip responses with repetition (the whole point!)
        if has_repetition(content):
            skipped_rep += 1
            continue

        # FILTER: Skip extremely long responses (>4000 chars)
        if len(content) > 4000:
            skipped_long += 1
            continue

        results.append({
            "messages": [m for m in msgs if m.get("role") in ("user", "assistant", "system")],
            "category": "reasoning_mot",
        })

        if len(results) >= n:
            break

    print(f"[mot] Sampled {len(results)} from {scanned} scanned "
          f"(skipped {skipped_rep} repetitive, {skipped_long} too long)", flush=True)
    return results


def load_openthoughts(n: int) -> list[dict]:
    """Load from open-thoughts/OpenThoughts-114k — DeepSeek-R1 traces."""
    from datasets import load_dataset

    print(f"[ot] Loading open-thoughts/OpenThoughts-114k...", flush=True)
    ds = load_dataset("open-thoughts/OpenThoughts-114k", split="train",
                      streaming=True)

    rng = random.Random(SEED + 1)
    results = []
    scanned = 0
    skipped_rep = 0

    for row in ds:
        scanned += 1
        if len(results) >= n:
            break
        if scanned > 100000:
            break

        if rng.random() > 0.15:
            continue

        convs = row.get("conversations", [])
        if not convs:
            continue
        msgs = sharegpt_to_messages(convs)
        if len(msgs) < 2:
            continue

        asst = next((m for m in msgs if m["role"] == "assistant"), None)
        if not asst:
            continue

        # Filter repetitive traces
        if has_repetition(asst["content"]):
            skipped_rep += 1
            continue

        # Compress very long think blocks
        content = asst["content"]
        if len(content) > 3000:
            # Keep first 2500 chars + last 500 chars
            content = content[:2500] + "\n...\n" + content[-500:]
            msgs = [m if m["role"] != "assistant" else
                    {**m, "content": content} for m in msgs]

        results.append({
            "messages": msgs,
            "category": "reasoning_openthoughts",
        })

    print(f"[ot] Sampled {len(results)} from {scanned} scanned "
          f"(skipped {skipped_rep} repetitive)", flush=True)
    return results


# ---------------------------------------------------------------------------
# Layer 2: Carry forward R5 instruction/format data
# ---------------------------------------------------------------------------

def load_r5_nonreasoning(n: int) -> list[dict]:
    """Load non-reasoning samples from R5 data (format, instruction, conv)."""
    r5_path = SPLITS / "r5_research_train.jsonl"
    if not r5_path.exists():
        print(f"[r5] R5 data not found at {r5_path}", flush=True)
        return []

    results = []
    with r5_path.open() as f:
        for line in f:
            row = json.loads(line)
            cat = row.get("category", "")
            # Keep non-reasoning categories
            if cat in ("format_constrained", "conversational", "code_concise",
                       "instruction_tulu3", "instruction_slimorca"):
                results.append(row)

    random.Random(SEED).shuffle(results)
    print(f"[r5] Loaded {min(len(results), n)} non-reasoning R5 samples", flush=True)
    return results[:n]


# ---------------------------------------------------------------------------
# Layer 3: Anti-loop data (loaded from pre-generated file)
# ---------------------------------------------------------------------------

def load_antiloop_data(path: Path) -> list[dict]:
    """Load anti-loop training pairs generated by generate_antiloop.py."""
    if not path.exists():
        print(f"[antiloop] No anti-loop data at {path}", flush=True)
        return []

    results = []
    with path.open() as f:
        for line in f:
            row = json.loads(line)
            results.append(row)

    print(f"[antiloop] Loaded {len(results)} anti-loop samples", flush=True)
    return results


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--antiloop-file", type=Path,
                    default=SPLITS / "antiloop_pairs.jsonl")
    ap.add_argument("--out-prefix", default="r6_antiloop")
    args = ap.parse_args()

    rng = random.Random(SEED)

    print("=" * 70)
    print("R6 DATA CURATION — Anti-Repetition Focus")
    print("=" * 70)

    all_data = []

    # Layer 1: Clean reasoning traces (filtered for non-repetition)
    mot = load_mixture_of_thoughts(1500)
    all_data.extend(mot)

    ot = load_openthoughts(1000)
    all_data.extend(ot)

    # Layer 2: Carry forward R5 instruction/format data
    r5 = load_r5_nonreasoning(1500)
    all_data.extend(r5)

    # Layer 3: Anti-loop correction data
    antiloop = load_antiloop_data(args.antiloop_file)
    all_data.extend(antiloop)

    # Shuffle
    rng.shuffle(all_data)

    n_total = len(all_data)
    n_train = int(n_total * 0.90)
    n_val = int(n_total * 0.05)

    train_data = all_data[:n_train]
    val_data = all_data[n_train:n_train + n_val]
    test_data = all_data[n_train + n_val:]

    prefix = args.out_prefix
    for name, data in [("train", train_data), ("val", val_data), ("test", test_data)]:
        path = SPLITS / f"{prefix}_{name}.jsonl"
        with path.open("w") as f:
            for row in data:
                f.write(json.dumps(row) + "\n")
        print(f"[write] {path.name}: {len(data)} samples")

    manifest = {
        "round": "r6-antiloop",
        "seed": SEED,
        "total": n_total,
        "train": n_train,
        "val": n_val,
        "test": len(test_data),
        "category_counts": {},
        "sha256_train": _sha(SPLITS / f"{prefix}_train.jsonl"),
        "sha256_val": _sha(SPLITS / f"{prefix}_val.jsonl"),
        "sha256_test": _sha(SPLITS / f"{prefix}_test.jsonl"),
    }
    for row in all_data:
        cat = row.get("category", "unknown")
        manifest["category_counts"][cat] = manifest["category_counts"].get(cat, 0) + 1

    (SPLITS / f"{prefix}_manifest.json").write_text(json.dumps(manifest, indent=2))

    print(f"\n{'='*70}")
    print(f"R6 DATASET SUMMARY")
    print(f"{'='*70}")
    print(f"Total: {n_total}  (train={n_train}, val={n_val}, test={len(test_data)})")
    print(f"\nCategory distribution:")
    for cat, count in sorted(manifest["category_counts"].items()):
        print(f"  {cat:<30} {count:>5} ({count/n_total*100:.1f}%)")
    print()


if __name__ == "__main__":
    main()
