#!/usr/bin/env python3
"""
Splice tool use into Ornith models from deepreinforce-ai and upload to Ollama.

Pulls GGUF models (or downloads raw weights and converts), creates Ollama
Modelfiles with proper tool-calling configuration (RENDERER/PARSER), and
registers them for agentic use.

Usage:
  python tool_splice.py 9b        # Splice & upload Ornith-1.0-9B
  python tool_splice.py 35b       # Splice & upload Ornith-1.0-35B
  python tool_splice.py both      # Do both 9b and 35b
  python tool_splice.py eval 9b   # Evaluate only
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OLLAMA_OUT = ROOT / "outputs" / "ollama"
LOGS = ROOT / "logs"

MODELS = {
    "9b": {
        "hf_repo": "deepreinforce-ai/Ornith-1.0-9B-GGUF",
        "tag": "ornith-1.0-9b-tools:q4km",
        "raw_hf": "deepreinforce-ai/Ornith-1.0-9B",
        "ollama_pull": "hf.co/deepreinforce-ai/Ornith-1.0-9B-GGUF:latest",
        "gguf_file": None,  # auto-detect from repo
        "out_name": "ornith-1.0-9b-tools-q4km",
    },
    "35b": {
        "hf_repo": "deepreinforce-ai/Ornith-1.0-35B-GGUF",
        "tag": "ornith-1.0-35b-tools:q4km",
        "raw_hf": "deepreinforce-ai/Ornith-1.0-35B",
        "ollama_pull": "hf.co/deepreinforce-ai/Ornith-1.0-35B-GGUF:latest",
        "gguf_file": None,
        "out_name": "ornith-1.0-35b-tools-q4km",
    },
}


def log(msg: str) -> None:
    print(f"[tool-splice] {msg}", flush=True)


def check_ollama() -> bool:
    return shutil.which("ollama") is not None


def ollama_has(tag: str) -> bool:
    if not check_ollama():
        return False
    result = subprocess.run(
        ["ollama", "list"],
        capture_output=True,
        text=True,
        timeout=30,
    )
    return tag.split(":")[0] in result.stdout


def pull_gguf_from_hf(cfg: dict) -> str | None:
    """Pull the GGUF model directly via ollama (fastest path)."""
    pull_tag = cfg["ollama_pull"]
    log(f"Pulling {pull_tag} via ollama...")
    result = subprocess.run(
        ["ollama", "pull", pull_tag],
        capture_output=True,
        text=True,
        timeout=600,
    )
    if result.returncode != 0:
        log(f"ollama pull failed: {result.stderr}")
        return None
    log("Pull complete.")
    return pull_tag


def create_tools_modelfile(cfg: dict, from_ref: str) -> Path:
    """Create a Modelfile with tool-calling configuration."""
    out_dir = OLLAMA_OUT / cfg["out_name"]
    out_dir.mkdir(parents=True, exist_ok=True)
    modelfile_path = out_dir / "Modelfile"

    # Determine FROM reference
    if from_ref.startswith("hf.co/"):
        from_line = f"FROM {from_ref}"
    elif from_ref.endswith(".gguf"):
        from_line = f"FROM ./{Path(from_ref).name}"
    else:
        from_line = f"FROM {from_ref}"

    modelfile_path.write_text(
        f"""# Generated by training_suite tool_splice.py
# Tool-calling-optimized Modelfile for {cfg["tag"]}

{from_line}

TEMPLATE {{{{ .Prompt }}}}

RENDERER qwen3.5
PARSER qwen3.5

PARAMETER num_ctx 262144
PARAMETER num_predict 16384
PARAMETER temperature 0.6
PARAMETER top_p 0.95
PARAMETER top_k 20
PARAMETER stop "<|im_end|>"
"""
    )
    log(f"Modelfile written: {modelfile_path}")
    return modelfile_path


def create_ollama_model(tag: str, modelfile: Path) -> bool:
    """Register the model in Ollama."""
    if ollama_has(tag):
        log(f"Model {tag} already exists in Ollama, skipping create.")
        return True
    log(f"Creating Ollama model {tag} from {modelfile}...")
    result = subprocess.run(
        ["ollama", "create", tag, "-f", str(modelfile)],
        capture_output=True,
        text=True,
        timeout=600,
    )
    if result.returncode != 0:
        log(f"ollama create failed: {result.stderr}")
        return False
    log(f"Model {tag} created successfully!")
    log(f"  Try: ollama run {tag}")
    return True


def run_eval(tag: str, label: str) -> dict:
    """Run capability gate and tool smoke tests."""
    results = {"model": tag, "label": label, "checks": {}}

    # Capability gate
    log(f"Running capability gate for {tag}...")
    try:
        from training_suite.evals.runner import capability_gate

        gate = capability_gate(tag)
        results["checks"]["capability_gate"] = gate
        log(f"  capability_gate ok={gate.get('ok')}")
    except Exception as e:
        log(f"  capability_gate error: {e}")
        results["checks"]["capability_gate"] = {"ok": False, "error": str(e)}

    # Tool smoke test
    log(f"Running tool smoke test for {tag}...")
    try:
        from training_suite.evals.runner import tool_smoke

        smoke = tool_smoke(tag)
        results["checks"]["tool_smoke"] = smoke
        log(f"  tool_smoke ok={smoke.get('ok')}")
    except Exception as e:
        log(f"  tool_smoke error: {e}")
        results["checks"]["tool_smoke"] = {"ok": False, "error": str(e)}

    # Save report
    report_path = LOGS / f"tool_splice_eval_{label.replace(':', '-')}.json"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(results, indent=2))
    log(f"Eval report saved: {report_path}")
    return results


def splice_model(size: str, do_eval: bool = True) -> bool:
    """Full splice pipeline for a given model size."""
    cfg = MODELS[size]
    log(f"{'=' * 60}")
    log(f"Splicing {cfg['tag']}")
    log(f"{'=' * 60}")

    # Step 1: Pull GGUF from HuggingFace via Ollama
    log("Step 1: Pulling GGUF model...")
    pull_tag = pull_gguf_from_hf(cfg)
    if not pull_tag:
        log("FAILED: Could not pull model.")
        return False

    # Step 2: Create Modelfile with tool-calling
    log("Step 2: Creating tool-calling Modelfile...")
    modelfile = create_tools_modelfile(cfg, pull_tag)

    # Step 3: Create Ollama model
    log("Step 3: Creating Ollama model...")
    if not create_ollama_model(cfg["tag"], modelfile):
        log("FAILED: Could not create Ollama model.")
        return False

    # Step 4: Evaluate
    if do_eval:
        log("Step 4: Running evaluations...")
        run_eval(cfg["tag"], cfg["out_name"])
    else:
        log("Step 4: Skipping eval.")

    log(f"DONE: {cfg['tag']} ready for agentic use!")
    return True


def main() -> None:
    if not check_ollama():
        log("ERROR: ollama CLI not found on PATH")
        sys.exit(1)

    args = sys.argv[1:]
    do_eval = "--no-eval" not in args
    args = [a for a in args if a != "--no-eval"]

    if not args or "both" in args:
        sizes = ["9b", "35b"]
    else:
        sizes = args

    ok = True
    for size in sizes:
        if size == "eval":
            continue
        if size.startswith("eval"):
            # Just eval an existing model
            tag_key = size.replace("eval-", "").replace("eval", "9b")
            cfg = MODELS.get(tag_key, MODELS["9b"])
            run_eval(cfg["tag"], cfg["out_name"])
            continue
        if size in MODELS:
            if not splice_model(size, do_eval=do_eval):
                ok = False
        else:
            log(f"Unknown size: {size}. Options: 9b, 35b, both")

    if not ok:
        sys.exit(1)


if __name__ == "__main__":
    main()
