from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from training_suite.core.config import DEFAULT_PARSER, DEFAULT_RENDERER


SECTION_NAMES = {
    "Model",
    "Capabilities",
    "Parameters",
    "Metadata",
    "Tensors",
    "License",
}


@dataclass
class OllamaShow:
    name: str
    exists: bool
    architecture: str | None = None
    parameters: str | None = None
    context_length: int | None = None
    embedding_length: int | None = None
    quantization: str | None = None
    capabilities: list[str] = field(default_factory=list)
    model: dict[str, str] = field(default_factory=dict)
    runtime_parameters: dict[str, str] = field(default_factory=dict)
    metadata: dict[str, str] = field(default_factory=dict)
    modelfile: str | None = None
    error: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "exists": self.exists,
            "architecture": self.architecture,
            "parameters": self.parameters,
            "context_length": self.context_length,
            "embedding_length": self.embedding_length,
            "quantization": self.quantization,
            "capabilities": self.capabilities,
            "model": self.model,
            "runtime_parameters": self.runtime_parameters,
            "metadata": self.metadata,
            "modelfile": self.modelfile,
            "error": self.error,
        }


@dataclass
class ModelfileSpec:
    from_ref: str
    renderer: str = DEFAULT_RENDERER
    parser: str = DEFAULT_PARSER
    parameters: dict[str, str | int | float] = field(default_factory=dict)
    license_text: str | None = None
    template: str | None = "{{ .Prompt }}"
    requires: str | None = None


def _parse_int(value: str | None) -> int | None:
    if not value:
        return None
    digits = re.sub(r"[^0-9]", "", value)
    return int(digits) if digits else None


def parse_ollama_show(text: str, name: str = "") -> OllamaShow:
    result = OllamaShow(name=name, exists=True)
    section: str | None = None
    for raw in text.splitlines():
        line = raw.rstrip()
        stripped = line.strip()
        if not stripped:
            continue
        if stripped in SECTION_NAMES:
            section = stripped
            continue
        if section == "Capabilities":
            if not re.search(r"\s{2,}", stripped) and stripped not in SECTION_NAMES:
                result.capabilities.append(stripped)
            continue
        if section in {"Model", "Parameters", "Metadata"}:
            m = re.match(r"^\s*([A-Za-z0-9_. -]+?)\s{2,}(.+?)\s*$", line)
            if not m:
                continue
            key = m.group(1).strip().replace(" ", "_").lower()
            value = m.group(2).strip()
            if section == "Model":
                result.model[key] = value
            elif section == "Parameters":
                result.runtime_parameters[key] = value
            else:
                result.metadata[key] = value

    result.architecture = result.model.get("architecture")
    result.parameters = result.model.get("parameters")
    result.context_length = _parse_int(result.model.get("context_length"))
    result.embedding_length = _parse_int(result.model.get("embedding_length"))
    result.quantization = result.model.get("quantization")
    return result


def ollama_available() -> bool:
    return shutil.which("ollama") is not None


def show_model(name: str, *, verbose: bool = False, include_modelfile: bool = False) -> OllamaShow:
    if not ollama_available():
        return OllamaShow(name=name, exists=False, error="ollama CLI not found on PATH")
    cmd = ["ollama", "show", name]
    if verbose:
        cmd.append("--verbose")
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    if proc.returncode != 0:
        return OllamaShow(
            name=name,
            exists=False,
            error=(proc.stderr or proc.stdout or "ollama show failed").strip(),
        )
    parsed = parse_ollama_show(proc.stdout, name=name)
    if include_modelfile:
        mf = subprocess.run(
            ["ollama", "show", name, "--modelfile"],
            capture_output=True,
            text=True,
            timeout=60,
        )
        if mf.returncode == 0:
            parsed.modelfile = mf.stdout
    return parsed


def generate_modelfile(spec: ModelfileSpec) -> str:
    lines = [
        "# Generated by training_suite",
        f"FROM {spec.from_ref}",
    ]
    if spec.template:
        lines.append(f"TEMPLATE {spec.template}")
    if spec.renderer:
        lines.append(f"RENDERER {spec.renderer}")
    if spec.parser:
        lines.append(f"PARSER {spec.parser}")
    if spec.requires:
        lines.append(f"REQUIRES {spec.requires}")
    for key, value in spec.parameters.items():
        if value is None or value == "":
            continue
        if isinstance(value, str) and (
            any(ch.isspace() for ch in value) or key == "stop" or any(ch in value for ch in "<>|")
        ):
            value = '"' + value.replace('"', '\\"') + '"'
        lines.append(f"PARAMETER {key} {value}")
    if spec.license_text:
        lines.append('LICENSE """')
        lines.append(spec.license_text.strip())
        lines.append('"""')
    return "\n".join(lines).rstrip() + "\n"


def write_modelfile(path: Path, spec: ModelfileSpec) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_modelfile(spec), encoding="utf-8")
    return path


def create_command(model_name: str, modelfile: Path) -> list[str]:
    return ["ollama", "create", model_name, "-f", str(modelfile)]


def signin_command() -> list[str]:
    return ["ollama", "signin"]


def copy_command(local_tag: str, remote_tag: str) -> list[str]:
    return ["ollama", "cp", local_tag, remote_tag]


def push_command(remote_tag: str) -> list[str]:
    return ["ollama", "push", remote_tag]


def capability_delta(detected: list[str], target: list[str]) -> dict[str, list[str]]:
    detected_set = set(detected)
    target_set = set(target)
    return {
        "present": sorted(detected_set & target_set),
        "missing": sorted(target_set - detected_set),
        "extra": sorted(detected_set - target_set),
    }
